services:
  api:
    build:
      context: .
      dockerfile: Api/Dockerfile
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ../db-init:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8000:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - app-network
 
  # front:
  #   image: front
  #   build: 
  #     context: ../front
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - "9000:80"

volumes:
  dbdata:
  
networks:
  app-network:
    driver: bridge